### ISSUE TITLE
Preserve YAML comments in front matter

### ISSUE THREAD

**Issue by hukkin** [butler54/mdformat-frontmatter#11]
I suggest using `ruamel.yaml` instead of `pyyaml` to preserve comments in YAML front matter.

**Comment by butler54** [comment]
Thanks - I'll have a look at that shortly.

**Comment by hukkin** [comment]
:+1: Btw, the ruamel.yaml API might be a bit more tricky than pyyaml. Here's an example how to use it (from another mdformat plugin) https://github.com/hukkinj1/mdformat-config/blob/228710f370f3a2a3ad019af7242beb71805316ce/mdformat_config/__init__.py#L20

**Comment by hukkin** [comment]
Closing this as ruamel.yaml is now being used.
