### ISSUE TITLE
AUR package?

### ISSUE THREAD

**Issue by gwpl** [butler54/mdformat-frontmatter#20]
Hello I've installed `mdformat` via AUR package https://aur.archlinux.org/packages/mdformat , 

AUR was way who I discovered mdformat.

maybe it is possible to either make it part of this package or make another AUR package to make it easy to discover for users ? - just idea

cross linkling: https://github.com/executablebooks/mdformat/issues/372#issuecomment-1526464845

**Comment by butler54** [comment]
Sorry for not getting back to you. I'll have a look in the next few weeks.

**Comment by butler54** [comment]
It looks like mdformat no longer has an AUR package?

**Comment by butler54** [comment]
I'm closing this on the basis that mdformat no longer has an AUR package and therefore it doesn't make sense to create one for this project. 

Happy to reopen if the state changes.
